# Pandocster configuration
pandocster:
  pandoc:
    bin: pandoc
    # Optional: list of paths to Lua filters, applied in order. If omitted, default filters are used.
    # filters:
    #   - /path/to/filter.lua
    # Metadata is passed to pandoc as is
    metadata:
      lang: ru
      toc-title: Оглавление
      # Arbitrary YAML structure; pandocster does not parse it, only writes to a temp file
      # and pass its path to pandoc via --metadata-file option.
      foo:
        bar: baz
        qux:
          - quux
    # Options and flags that are passed to pandoc as is
    options:
      - name: toc-depth
        value: 3
      - name: standalone
        value: true
